import Head from 'next/head';
import Header from './header';
import Colors from './colors';
import { Grid } from '@mui/material';
import TitlebarBelowImageList from './photo';
import SimpleGrow from './grow';

export default function Home() {
  return (
    <>
    <Head>
      <title>Next_prac</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <Grid container direction="column">
      <Header />
      <div style={{ padding: 30 }}>
        <Colors />
        <SimpleGrow/>
        <TitlebarBelowImageList />
      </div>
    </Grid>
    </>
  )
}
